import { Router } from "express";
import { connectMongo, Submission } from "../db/index.js";
import { sendSubmissionEmail, getTransporter } from "../lib/email.js";

const router = Router();

router.get("/test-email", async (req, res) => {
  try {
    const transporter = getTransporter();
    if (!transporter) {
      res.status(400).json({ 
        success: false, 
        message: "SMTP not configured. SMTP_USER or SMTP_PASS environment variables are missing." 
      });
      return;
    }

    // Verify connection configuration
    await transporter.verify();

    // Send diagnostic email
    const info = await transporter.sendMail({
      from: `"Soaring Aerotech Diagnostics" <harshsoaring@gmail.com>`,
      to: "info@soaringaerotech.com",
      subject: "SMTP Connection Diagnostics Test",
      html: `
        <div style="font-family: sans-serif; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;">
          <h2 style="color: #22c55e;">SMTP Connection Successful!</h2>
          <p>This is a diagnostic test email generated by the Soaring Aerotech backend.</p>
          <p>If you received this message, it means your SMTP configuration is correct and emails are active.</p>
          <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
          <small style="color: #64748b;">Timestamp: ${new Date().toISOString()}</small>
        </div>
      `,
    });

    res.json({ 
      success: true, 
      message: "SMTP connection verified and test email sent successfully!", 
      messageId: info.messageId 
    });
  } catch (error) {
    res.status(500).json({ 
      success: false, 
      message: "SMTP verification failed", 
      error: error.message,
      code: error.code,
      command: error.command
    });
  }
});

router.post("/submit", async (req, res) => {
  try {
    await connectMongo();

    const { type, name, phone, email, subject, program, message } = req.body;

    if (!type || !name || !phone) {
      res.status(400).json({ success: false, error: "name and phone are required" });
      return;
    }

    const doc = await Submission.create({
      type,
      name,
      phone,
      email,
      subject,
      program,
      message,
    });

    // Trigger email notification asynchronously
    sendSubmissionEmail({
      type,
      name,
      phone,
      email,
      subject,
      program,
      message,
    }).catch((err) => {
      console.error("Failed to send email notification:", err);
    });

    res.json({ success: true, id: doc._id });
  } catch (err) {
    res.status(500).json({ success: false, error: "Failed to save submission" });
  }
});

export default router;
