import { Router } from "express";
import { connectMongo, Submission } from "../db/index.js";
import { sendSubmissionEmail, getTransporter } from "../lib/email.js";

const router = Router();

router.get("/test-email", async (req, res) => {
  try {
    const transporter = getTransporter();
    if (!transporter) {
      res.status(400).json({ 
        success: false, 
        message: "SMTP not configured. SMTP_USER or SMTP_PASS environment variables are missing." 
      });
      return;
    }

    // Verify connection configuration
    await transporter.verify();

    // Send diagnostic email
    const info = await transporter.sendMail({
      from: `"Soaring Aerotech Diagnostics" <harshsoaring@gmail.com>`,
      to: "info@soaringaerotech.com, harshsoaring@gmail.com",
      subject: "SMTP Connection Diagnostics Test",
      html: `
        <div style="font-family: sans-serif; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;">
          <h2 style="color: #22c55e;">SMTP Connection Successful!</h2>
          <p>This is a diagnostic test email generated by the Soaring Aerotech backend.</p>
          <p>If you received this message, it means your SMTP configuration is correct and emails are active.</p>
          <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
          <small style="color: #64748b;">Timestamp: ${new Date().toISOString()}</small>
        </div>
      `,
    });

    res.json({ 
      success: true, 
      message: "SMTP connection verified and test email sent successfully!", 
      messageId: info.messageId 
    });
  } catch (error) {
    res.status(500).json({ 
      success: false, 
      message: "SMTP verification failed", 
      error: error.message,
      code: error.code,
      command: error.command
    });
  }
});

router.post("/submit", async (req, res) => {
  try {
    await connectMongo();

    const { type, name, phone, email, subject, program, message } = req.body;
    console.log("📝 Incoming form submission:", { type, name, phone, email, subject, program, message });

    if (!type || !name || !phone) {
      console.warn("⚠️ Validation failed: type, name, or phone is missing.");
      res.status(400).json({ success: false, error: "name and phone are required" });
      return;
    }

    const doc = await Submission.create({
      type,
      name,
      phone,
      email,
      subject,
      program,
      message,
    });
    console.log("✅ Form submission saved successfully to DB, ID:", doc._id);

    // Trigger email notification asynchronously
    console.log("📧 Triggering email notification...");
    sendSubmissionEmail({
      type,
      name,
      phone,
      email,
      subject,
      program,
      message,
    }).then((emailResult) => {
      console.log("📧 Email notification response:", emailResult);
    }).catch((err) => {
      console.error("❌ Failed to send email notification:", err);
    });

    res.json({ success: true, id: doc._id });
  } catch (err) {
    console.error("❌ Database error during form submission:", err);
    res.status(500).json({ success: false, error: "Failed to save submission" });
  }
});

router.get("/submissions", async (req, res) => {
  try {
    await connectMongo();
    const token = req.headers.authorization;
    if (token !== "Bearer soaring-admin-token-12345") {
      res.status(401).json({ success: false, error: "Unauthorized access" });
      return;
    }

    const list = await Submission.find({}).sort({ createdAt: -1 });
    res.json({ success: true, data: list });
  } catch (err) {
    console.error("❌ Failed to fetch submissions:", err);
    res.status(500).json({ success: false, error: "Failed to fetch submissions" });
  }
});

router.delete("/submissions/:id", async (req, res) => {
  try {
    await connectMongo();
    const token = req.headers.authorization;
    if (token !== "Bearer soaring-admin-token-12345") {
      res.status(401).json({ success: false, error: "Unauthorized access" });
      return;
    }

    const { id } = req.params;
    await Submission.findByIdAndDelete(id);
    res.json({ success: true, message: "Submission deleted successfully" });
  } catch (err) {
    console.error("❌ Failed to delete submission:", err);
    res.status(500).json({ success: false, error: "Failed to delete submission" });
  }
});

router.put("/submissions/:id/read", async (req, res) => {
  try {
    await connectMongo();
    const token = req.headers.authorization;
    if (token !== "Bearer soaring-admin-token-12345") {
      res.status(401).json({ success: false, error: "Unauthorized access" });
      return;
    }

    const { id } = req.params;
    const { read } = req.body;
    const doc = await Submission.findByIdAndUpdate(
      id,
      { read: read !== undefined ? read : true },
      { new: true }
    );
    res.json({ success: true, data: doc });
  } catch (err) {
    console.error("❌ Failed to update read status:", err);
    res.status(500).json({ success: false, error: "Failed to update read status" });
  }
});

export default router;
